# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-23 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cs',
            field=models.CharField(default='cs1', max_length=2000),
        ),
    ]
