# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-23 07:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_ss'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ss',
        ),
        migrations.RemoveField(
            model_name='user',
            name='cs',
        ),
    ]
