# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-23 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kindle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_img',
            field=models.CharField(default='http://', max_length=2000),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_raw_name',
            field=models.CharField(max_length=2000, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_simple_name',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_url',
            field=models.CharField(default='http://', max_length=2000),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(max_length=100000),
        ),
        migrations.AlterField(
            model_name='mark',
            name='content',
            field=models.TextField(max_length=100000),
        ),
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.TextField(max_length=100000),
        ),
    ]
