# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-23 06:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kindle', '0002_auto_20170923_0625'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book_img',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='book_raw_name',
            new_name='raw_name',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='book_simple_name',
            new_name='simple_name',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='book_url',
            new_name='url',
        ),
    ]
