# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-23 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kindle', '0003_auto_20170923_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='find_page',
            field=models.CharField(max_length=100),
        ),
    ]
